# Generated by Django 4.2 on 2024-02-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PE', 'Gözləmədə'), ('PR', 'İşlənilir'), ('SP', 'Yoldadır'), ('DL', 'Çatdırıldı'), ('CL', 'Ləğv edildi')], default='PE', max_length=2),
        ),
    ]
